### ISSUE TITLE
[FEATURE REQUEST] Compatibility with Expanded Storage

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [QuiltServerTools/HeyThatsMine#14]
Could you please add possibility to manage containers created with [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric) mod? Currently, attempting to do so results in a “Block not lockable” message.

**Comment by PotatoPresident** [comment]
Hey That's Mine should be compatible with all containers. If it says it's not lockable, the mods hasn't implemented containers correctly and is extending regular BlockEntity instead of LockableContainerBlockEntity like all vanilla and modded containers should. Expanded Storage is also licensed under All Rights Reserved so I can't really do anything. Create an issue on their github.
